Set up a "Hello Microverse" project
Lawmsangi/hello-microverse pull request #1
Opened 2023-05-30 16:50 UTC by Lawmsangi

1. I  create a new branch according to the GitHub flow rules.
2. I set up a linter for HTML and CSS and make sure that any files that are not relevant are ignored by git.
3. I add node_modules to .gitignore.
4. I add index.html with h1 tag containing "Hello Microverse!".
5. I give color to h1 tag using CSS.
6. I add test.md file.
7. I add test.md file to .gitignore.

2023-05-30 17:01 UTC, Zuhaib042 requested changes
Hi @Lawmsangi 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif)

## Highlights
✅ Descriptive PR
✅ Professional Readme

## Required Changes ♻️
- [x] Kindly consider writing descriptive commit messages in imperative tense, so instead of `Added homepage`, you can write `Add homepage to project`
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 17:01 UTC, Zuhaib042 commented on README.md
> +  <img src="murple_logo.png" alt="logo" width="140"  height="auto" />
- [ ] kindly consider removing this line from here as having broken images in our readme make it unprofessional. if you have your own logo, you can place it here.

2023-05-30 17:01 UTC, Zuhaib042 commented on README.md
> +To run tests, run the following command:
- [ ] Kindly consider removing this line no 99, as it has no meaning when you write in the next line that there is no test.

2023-05-30 17:01 UTC, Zuhaib042 commented on README.md
> +You can deploy this project using:
[ ] Kindly consider removing this line no 104, as it has no meaning when you write in the next line that there is no deployment.

2023-05-31 06:10 UTC, Johnadibe approved these changes
# Status: Approved ✔️
### Hi @Lawmsangi👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

## Highlights
- Good commit history✔️
- Descriptive PR✔️
- Professional README Documentation✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 06:11 UTC, merged